[build]
  command = "npm run build"  # Specify the build command for your project
  publish = "build"          # Specify the directory to publish

[context.deploy-preview.environment]  # Set environment variables for deploy previews
  STRIPE_KEY = "sk_test_51NHYkcK1Xa4n6v2jFPsCrIdSt9obXywrdFbQYXNufVZxQD4aKdPvZHh9crgjdRJ7Cq6Oyn3oDXAu7fksszK2wIlt00xKKogGZ6"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"